# Generated by Django 5.0.7 on 2024-09-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_category_options_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='date_created',
        ),
    ]
